-- DAKKHO Admin Panel - Edge Functions Secrets
-- Run these commands in Supabase Dashboard > Edge Functions > Secrets
-- OR via CLI: supabase secrets set KEY=VALUE

-- Required secrets for Edge Functions:
-- APPWRITE_ENDPOINT=https://sgp.cloud.appwrite.io/v1
-- APPWRITE_PROJECT_ID=dakkho
-- APPWRITE_DATABASE_ID=dakkho_main
-- APPWRITE_API_KEY=<set-via-wrangler-secret-put>
-- R2_ACCESS_KEY_ID=<set-via-wrangler-secret-put>
-- R2_SECRET_ACCESS_KEY=<set-via-wrangler-secret-put>
-- R2_ENDPOINT=<set-via-wrangler-secret-put>
-- R2_BUCKET_VIDEOS=dakkho-videos
-- R2_BUCKET_THUMBNAILS=dakkho-thumbnails
-- R2_BUCKET_AVATARS=dakkho-avatars
-- R2_BUCKET_RESOURCES=dakkho-resources
-- RESEND_API_KEY=<set-via-wrangler-secret-put>
-- RESEND_FROM_EMAIL=noreply@dakkho.pro.bd
-- ADMIN_SECRET_KEY=<set-via-wrangler-secret-put>
